//조건부 랜더링을 활용하여 로그인페이지에서 /a,c 섹션 안보이게함

import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { LogOutBtn } from "./LogOutBtn";
import LoginBtn from "./LoginBtn";
import { Box, Grid, Button } from "@mui/material";
import Sidebar from "./Sidebar/page";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  //서버에서 세션 가져와 로그인된 유저정보 출력
  console.log(children)
  return (
    <html lang="en">
      <head />
      <body>
        {/* 이거 넣으면 경로는 바로 바뀜 */}
        {/* {pathname === "/auth/login" ? <>{children} </>
        : */}
        <Box>
          <Grid container spacing={1}>
            <Grid container spacing={1} sx={{ flexDirection: 'row', flexWrap: 'nowrap' }}>
              {/* C 섹션: 상단 Nav 바 */}
              <Grid item xs={12}>
                <Box className="navbar">
                  <img src="/IDIS_Basic.png" alt="Idis" style={{ width: '80px', marginBottom: '-5px' }} /> {/* 로고 이미지 */}
                  {'　　'} {/* 공백 추가 */}       {/* 이미지 추가 */}
                  
                  {session ? ( // 조건부 랜더링. 세션이 존재하는 경우에만 Nav 바와 버튼들을 렌더링합니다.
                    <>
                      <span><b>{session.user.userId}</b> <LogOutBtn /></span> {/* 로그인된 사용자 정보와 로그아웃 버튼 */}
                      {'　　　　'} {/* 공백 추가 */}
                      <Button component={Link} href="/" className="button-navbar">HOME</Button>
                      <Button component={Link} href="/ptable" className="button-navbar">ptable</Button>
                      <Button component={Link} href="/account" className="button-navbar" color="info">계정관리</Button>
                    </>
                  ) :
                  
                  ( // 세션이 없을 경우 로그인 버튼만 렌더링합니다.
                    <>
                      <LoginBtn /> {/* 로그인 버튼 */}
                      {'　'}
                      <Button component={Link} href="/logInOut/login" variant="contained" color="info">세션 로그인</Button>
                    </>
                  )}
                </Box>
              </Grid>
            </Grid>

            {/* A 섹션: 사이드바 */}
            {session && ( // 세션이 존재하는 경우에만 사이드바를 렌더링합니다. ,&& 이 조건부 랜더링
              <Grid
                item
                // xs={1.5}   // sx속성에 width 를 픽셀로 입력하지 않고, xs 값을 12로 나누어서 설정할수도 있음
                sx={{
                  display: { xs: 'none', lg: 'block' }, // 작은 화면에서는 숨기고, 큰 화면에서는 보이게 설정합니다.
                  borderRight: '1px solid lightgrey', // 우측 라인
                  height: '120vh',
                  width: '220px'
                }}
              >
                <Sidebar />
              </Grid>
            )}

            <Grid
              item
              xs
              sx={{
                overflow: 'auto', // 내용이 넘칠 경우 스크롤바 표시
                minWidth: '300px', // 최소 너비 설정
              }}
            >
              {children}
              {/* B구역 메인*/}
            </Grid>
          </Grid>
        </Box>

        {/* } */}
        {/* 이거 넣으면 경로는 바로 바뀜 */}
      </body>
    </html>
  );
}
