import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { LogOutBtn } from "./LogOutBtn";
import LoginBtn from "./LoginBtn";
import { Box, Grid, Button } from "@mui/material";
import Sidebar from "./Sidebar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 임의의 경로를 지정
const pathname = "/auth/login";

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions); // 서버에서 세션을 가져옵니다.
  
  //로그인된 유저정보 출력
  console.log(children);

  return (
    <html lang="en">
      <head />
      <body>
        {/* 이거 넣으면 경로 는 바로 바뀜 */}
        {/* {pathname === "/auth/login" ? <>{children} </>
        : */}
        <Box>
          <Grid container spacing={1}>
            <Grid container spacing={1} sx={{ flexDirection: 'row', flexWrap: 'nowrap' }}>
              {/* C 구역 상단 Nav bar */}
              <Grid item xs={12}>
                {session ? ( // 세션이 있는 경우에만 C 섹션을 렌더링합니다.
                  <Box className="navbar">
                    <img src="/IDIS_Basic.png " alt="Idis" style={{ width: '80px', marginBottom: '-5px' }} /> {/* 이미지 추가 */}
                    {'　　'} {/* 공백 추가 */}
                    {/* 서버컴포넌트라서 사용불가. 클라이언트 컴포넌트를 가져옴
                    {/* <Logout/> */}
                    <span><b>{session.user.userId}</b> <LogOutBtn /></span> {/* 로그인된 사용자 정보와 로그아웃 버튼 */}
                    {'　'} {/* 공백 추가 */}
                    <Button component={Link} href="/logInOut/login" variant="contained" color="info">세션 로그인</Button>
                    {'　'} {/* 공백 추가 */}
                    {/* <Button component={Link} href="/pjoin" variant="contained" color="error">평문 로그인</Button> */}
                    {'　　　　'} {/* 공백 추가 */}
                    {/* <Button component={Link} href="/writetest" variant="contained" color="secondary">post, wrtietest</Button> */}
                    <Button component={Link} href="/" className="button-navbar">HOME</Button>
                    <Button component={Link} href="/ptable" className="button-navbar">ptable</Button>
                    <Button component={Link} href="/account" className="button-navbar" color="info">계정관리</Button>
                  </Box>
                ) : null}
              </Grid>
            </Grid>

            {/* A 섹션 반응형으로 수정 */}
            {session ? ( // 세션이 있는 경우에만 A 섹션을 렌더링합니다.
              <Grid
                item
                // xs={1.5}   // sx속성에 width 를 픽셀로 입력하지 않고, xs 값을 12로 나누어서 설정할수도 있음
                sx={{
                  display: { xs: 'none', lg: 'block' }, // xs 크기에서는 숨기고, xl 크기 이상에서는 보이게 설정[블럭]
                  borderRight: '1px solid lightgrey',
                  height: '120vh',
                  width: '220px'
                }}
              >
                {/* A섹션에 우측에 선그려서 섹션구분 */}
                <Sidebar />
              </Grid>
            ) : null}
            {/* A 섹션 반응형으로 수정 */}

            <Grid
              item
              xs
              sx={{
                overflow: 'auto', // 내용이 넘칠 경우 스크롤바 표시
                minWidth: '300px', // 최소 너비 설정
              }}
            >
              {children}
              {/* B구역 */}
            </Grid>
          </Grid>
        </Box>
        
        {/* } */}  
        {/* 이거 넣으면 경로는 바로 바뀜 */}
        

      </body>
    </html>
  );
}