import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";


import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { LogOutBtn } from "./LogOutBtn";
import LoginBtn from "./LoginBtn";
import { Stack, Container, Link as MuiLink } from "@mui/material";
import { Drawer, List, ListItem, ListItemText, Divider,  Accordion, AccordionSummary, AccordionDetails, Box, Grid, Typography, Button } from "@mui/material";
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';


import Sidebar from "./Sidebar/page";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  console.log(session)
  return (
   
    <html lang="en">
      <head />
      <body>
      <Box>
      <Grid container spacing={1}>
        <Grid container >
          <Grid item xs={12}>
            <Box className="navbar">
            <img src="/IDIS_Basic.png " alt="Idis" style={{ width: '80px', marginBottom: '-5px' }} /> {/* 이미지 추가 */}
        {/* 이미지 추가 */}
        {'　　'} {/* 공백 추가 */}
        {session
          ? <span><b>{session.user.name}</b> <LogOutBtn></LogOutBtn> </span>
          : <LoginBtn></LoginBtn>
          // 조건식 ? 조건식참일때 남길html : 거짓일때 남길html
        }
         {'　'} {/* 공백 추가 */}
        <Button component={Link} href="/pjoin" variant="contained" color="error">계정 생성</Button>
        {'　　　　'} {/* 공백 추가 */}
        {/* <Button component={Link} href="/writetest" variant="contained" color="secondary">post, wrtietest</Button> */}
        <Button component={Link} href="/ptable" variant="contained" color="secondary">ptable</Button>
        <Button component={Link} href="/account" variant="contained" color="secondary">계정관리</Button>
        <Button component={Link} href="/accodion" variant="contained" color="secondary">DB 관리</Button>
        <Button component={Link} href="/test/gettest" variant="contained" color="secondary">get, test</Button>
        <Button component={Link} href="/" variant="contained" >HOME</Button>
              {/* {/* <Typography variant="h5" color="white">
                C 구역 상단 Nav bar
              </Typography> */}
         
            </Box>
          </Grid>
        </Grid>

        <Grid item xs={1}>
        <Box sx={{ borderRight: '1px solid lightgrey', height: '100vh' }}>
        
          {/* A섹션에 우측에 선그려서 섹션구분 */}
            <Sidebar/>
            <Typography variant="h5" color="white">
              A 구역
            </Typography>
            <Typography variant="body1" color="white">
                좌측 설명구역
            </Typography>
          </Box>
        </Grid>
        <Grid item xs={11}>
          <Box >
          {children}
        
            {/* <Typography variant="h5" color="white">
              B 구역
            </Typography>
            <Typography variant="body1" color="white">
                우측 구역
            </Typography> */}
          </Box>
        </Grid>
      </Grid>
    </Box>
        
      </body>
    </html>
  );
}


